version: "3"

services:
  web:
    container_name: web
    build: ./client/
    command: yarn serve
    ports:
      - 3000:8080
    depends_on:
      - api-gateway
    volumes:
      - ./client:/app/client
      - /app/client/node_modules

  api-gateway:
    container_name: api-gateway
    build: ./services/gateway/
    command: yarn dev
    ports:
      - 5000:5000
    environment:
      - USER_SERVICE_HOST=http://users-service:5001
      - TASK_SERVICE_HOST=http://tasks-service:5002
    depends_on:
      - users-service
      - tasks-service
    volumes:
      - ./services/gateway:/app/services/gateway
      - /app/services/gateway/node_modules

  users-service:
    container_name: users-service
    build: ./services/users/
    command: yarn dev
    ports:
      - 5001:5001
    depends_on:
      - postgres
    volumes:
      - ./services/users:/app/services/users
      - /app/services/users/node_modules

  tasks-service:
    container_name: tasks-service
    build: ./services/tasks/
    command: yarn dev
    ports:
      - 5002:5002
    depends_on:
      - postgres
    volumes:
      - ./services/tasks:/app/services/tasks
      - /app/services/tasks/node_modules

  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
